name: Build with Maven

on:
  push:
    branches: [ 3.x ]
  pull_request:
    branches: [ 3.x ]
  workflow_dispatch:

jobs:
  build:
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/build-backend-module.yml@main
    with:
      java_versions: '["8"]'
      main_java_version: '8'
      maven_args: 'clean install -Dmaven.javadoc.skip=true'
      deploy_branch: '3.x'
    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
      MAVEN_REPO_API_KEY: ${{ secrets.MAVEN_REPO_API_KEY }}
      BOT_GH_TOKEN: ${{ secrets.OMRS_BOT_GH_TOKEN }}
