name: Build with Maven

on:
  push:
    branches: [ 2.x ]
  pull_request:
    branches: [ 2.x ]
  workflow_dispatch:

jobs:
  build:
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/build-backend-module.yml@main
    with:
      maven_args: 'clean install -Dmaven.javadoc.skip=true'
      deploy_branch: '2.x'
    secrets:
      MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
      MAVEN_REPO_API_KEY: ${{ secrets.MAVEN_REPO_API_KEY }}
