name: Release Module

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., 3.2.0)'
        required: true
      development_version:
        description: 'Next development version (e.g., 3.3.0-SNAPSHOT)'
        required: true
      branch:
        description: 'Branch to release from (e.g., 3.x)'
        required: true

jobs:
  release:
    name: Release
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/release-backend-module.yml@main
    with:
      release_version: ${{ inputs.release_version }}
      development_version: ${{ inputs.development_version }}
      branch: ${{ inputs.branch }}
    secrets:
      MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
      MAVEN_REPO_API_KEY: ${{ secrets.MAVEN_REPO_API_KEY }}
