name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., 1.3.3)'
        required: true
      development_version:
        description: 'Next development version (e.g., 1.4.0-SNAPSHOT)'
        required: true
      branch:
        description: 'Branch to release from (e.g., master)'
        required: false
        default: '2.x'

jobs:
  release:
    uses: openmrs/openmrs-contrib-gha-workflows/.github/workflows/release-backend-module.yml@main
    permissions:
      contents: write
    with:
      release_version: ${{ inputs.release_version }}
      development_version: ${{ inputs.development_version }}
      branch: ${{ inputs.branch }}
      create_github_release: true
    secrets:
      MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
      MAVEN_REPO_API_KEY: ${{ secrets.MAVEN_REPO_API_KEY }}
      BOT_PAT: ${{ secrets.OMRS_BOT_PAT }}
